export interface InterestCategory {
  title: string;
  emoji: string;
  options: string[];
}

export const INTEREST_CATEGORIES: InterestCategory[] = [
  {
    title: 'Creativity',
    emoji: '🎨',
    options: [
      'Photography',
      'Choir',
      'Singing',
      'Poetry',
      'Writing',
      'Literature',
      'Painting',
      'Musical Instrument',
      'Dancing',
      'Art',
      'Drawing',
      'Fashion',
      'DIY',
      'Content Creation',
    ],
  },
  {
    title: 'Faith Community',
    emoji: '⛪',
    options: [
      'Bible Study Group',
      'Prayer Circle',
      'Youth Fellowship',
      'Singles Fellowship',
      'Campus Fellowship',
      'Cell Group',
      'Discipleship Class',
      'Evangelism Team',
      'Prayer Retreats',
      'Christian Conferences',
      'Family Fellowship',
      'Community Fellowship',
    ],
  },
  {
    title: 'Food and Drink',
    emoji: '🍽️',
    options: [
      'Foodie',
      'Food Tours',
      'Mocktails',
      'Sweet Treats',
      'Brunch',
      'Street Food',
      'Plant-based',
      'Coffee',
      'Tea',
      'Ice Cream',
      'BBQ',
      'Baking',
    ],
  },
  {
    title: 'Going Out',
    emoji: '🌐',
    options: [
      'Museums',
      'Cafe Hopping',
      'Shopping',
      'Festivals',
      'Live Music',
      'Theater',
      'Exhibition',
      'Thrifting',
      'Community Events',
      'Charity Events',
    ],
  },
  {
    title: 'Music Artists',
    emoji: '🎵',
    options: [
      'Lawrence Oyor',
      'Theophilus Sunday',
      'Dunsin Oyekan',
      'Nathaniel Bassey',
      'Moses Bliss',
      'Mercy Chinwo',
      'Sinach',
      'Ada Ehi',
      'Frank Edwards',
      'Judikay',
      'Neon Adejo',
      'Peterson Okopi',
      'Joe Praize',
      'Eben',
    ],
  },
  {
    title: 'Outdoors and Adventure',
    emoji: '🏕️',
    options: [
      'Nature',
      'Travel',
      'Road Trips',
      'Hiking',
      'Camping',
      'Picnicking',
      'Mountains',
      'Fishing',
      'Beach',
      'Walking Tours',
    ],
  },
  {
    title: 'Ministry and Service',
    emoji: '🤝',
    options: [
      'Choir Ministry',
      'Ushering',
      'Children Ministry',
      'Media Ministry',
      'Prayer Ministry',
      'Hospital Visitation',
      'Prison Outreach',
      'Street Evangelism',
      'Mentorship',
      'Charity Work',
      'Hospitality Team',
      'Counseling Support',
    ],
  },
  {
    title: 'Kingdom Lifestyle',
    emoji: '🕊️',
    options: [
      'Daily Devotion',
      'Scripture Memorization',
      'Morning Prayer',
      'Night Vigil',
      'Fasting',
      'Journaling with God',
      'Faith Conversations',
      'Christian Podcasts',
      'Sermon Notes',
      'Worship Nights',
      'Marriage Preparation',
      'Personal Growth',
    ],
  },
  {
    title: 'Church Life',
    emoji: '🙏',
    options: [
      'Sunday Service',
      'Midweek Service',
      'Communion Service',
      'Prayer Meetings',
      'Workers Meeting',
      'Leadership Training',
      'Church Events',
      'Volunteering at Church',
      'Testimony Sharing',
      'New Converts Care',
      'Church Missions',
      'Church Media',
    ],
  },
  {
    title: 'Relationship and Family Values',
    emoji: '💍',
    options: [
      'Purposeful Dating',
      'Courtship with Intent',
      'Family Devotion',
      'Respect and Honor',
      'Accountability',
      'Healthy Communication',
      'Emotional Maturity',
      'Conflict Resolution',
      'Serving Together',
      'Purity Culture',
      'Faith-Centered Home',
      'Parenting Values',
    ],
  },
  {
    title: 'Values and Causes',
    emoji: '🌍',
    options: [
      'Mental Health Awareness',
      'Social Development',
      'Human Rights',
      'Inclusivity',
      'World Peace',
      'Youth Empowerment',
      'Equality',
      'Volunteering',
      'Climate Change',
      'Community Service',
    ],
  },
  {
    title: 'Wellness and Lifestyle',
    emoji: '🌿',
    options: [
      'Self Care',
      'Meditation',
      'Mindfulness',
      'Skincare',
      'Active Lifestyle',
      'Trying New Things',
      'Self Development',
    ],
  },
];
