export const PROFILE_PROMPT_OPTIONS: string[] = [
  'My testimony in one line is...',
  'The verse shaping my season is...',
  "A prayer God answered for me was...",
  'My life completely changed when...',
  'A Christ-centered relationship means...',
  'A life goal I am praying for...',
  'Typical Sunday after church...',
  'Two truths and a prayer request...',
  'A ministry or outreach I care about is...',
  'My favorite worship song right now is...',
  'One way I serve in church is...',
  'My ideal devotion time looks like...',
  'A faith value I will never compromise on is...',
  'My parents will like you if...',
  "I'm the person my friends call when...",
  'I am known for...',
  'My happy place is...',
  'I feel most alive when...',
  'One thing people misunderstand about me is...',
  'I recharge by...',
  'Something I am grateful for lately is...',
  'A dream I am working toward is...',
  'A skill I would love to improve is...',
  'My favorite way to spend a free day is...',
  'A meaningful connection to me looks like...',
  'I appreciate someone who...',
  'I feel closest to someone when...',
  'A healthy relationship includes...',
  'Mutual respect to me means...',
  'Trust is built when...',
];

export const BIO_MAX_LENGTH = 500;
export const PROMPT_ANSWER_MAX_LENGTH = 150;
